version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Comforter
      POSTGRES_DB: postgres
      POSTGRES_HOST: database-2.cucgu00d8nwd.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: microserve-s3-bucket
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Comforter 
      POSTGRES_DB: postgres
      POSTGRES_HOST: database-2.cucgu00d8nwd.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      AWS_BUCKET: microserve-s3-bucket
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    # command: ng serve
    ports:
      - "8100:80"