apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: opetoyemi/udagram-api-feed:v3
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: env-secret
              key: postgres
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: env-secret
              key: Comforter1
        - name: POSTGRES_HOST
          valueFrom: 
            secretKeyRef: 
              name: env-configmap
              key: database-1.cucgu00d8nwd.us-east-1.rds.amazonaws.com 
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef: 
              name: env-configmap
              key: postgres

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed
