apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: docker.io/opetoyemi/udagram-reverseproxy:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m